//
//  SnakeSegments.swift
//  SnakeGame
//
//  Created by PavelPopov on 07.09.16.
//  Copyright (c) 2016 PixelCut. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SnakeSegments : NSObject {

    //// Cache

    private struct Cache {
        static let bodyColor: UIColor = UIColor(red: 0.000, green: 1.000, blue: 0.338, alpha: 1.000)
        static let foodColor: UIColor = UIColor(red: 1.000, green: 0.000, blue: 0.000, alpha: 1.000)
    }

    //// Colors

    public class var bodyColor: UIColor { return Cache.bodyColor }
    public class var foodColor: UIColor { return Cache.foodColor }

    //// Drawing Methods

    public class func drawHeadSymbol(open open: Bool = false, angle: CGFloat = 90) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let bodyColor2 = SnakeSegments.bodyColor.colorWithShadow(0.5)

        //// Variable Declarations
        let endAngle: CGFloat = open ? 125 : 90
        let startAngle: CGFloat = open ? 415 : 450

        //// Oval Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 30, 30)
        CGContextRotateCTM(context, -angle * CGFloat(M_PI) / 180)

        let ovalRect = CGRect(x: -25, y: -25, width: 50, height: 50)
        let ovalPath = UIBezierPath()
        ovalPath.addArcWithCenter(CGPoint(x: ovalRect.midX, y: ovalRect.midY), radius: ovalRect.width / 2, startAngle: -startAngle * CGFloat(M_PI)/180, endAngle: -endAngle * CGFloat(M_PI)/180, clockwise: true)
        ovalPath.addLineToPoint(CGPoint(x: ovalRect.midX, y: ovalRect.midY))
        ovalPath.closePath()

        SnakeSegments.bodyColor.setFill()
        ovalPath.fill()
        bodyColor2.setStroke()
        ovalPath.lineWidth = 2
        ovalPath.stroke()

        CGContextRestoreGState(context)
    }

    public class func drawHead(open open: Bool = false, angle: CGFloat = 90, bounds: CGRect = CGRect(x: 0, y: 0, width: 60, height: 60)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Symbol Drawing
        let symbolRect = CGRect(x: bounds.origin.x, y: bounds.origin.y, width: bounds.size.width, height: bounds.size.height)
        CGContextSaveGState(context)
        UIRectClip(symbolRect)
        CGContextTranslateCTM(context, symbolRect.origin.x, symbolRect.origin.y)
        CGContextScaleCTM(context, symbolRect.size.width / 60, symbolRect.size.height / 60)

        SnakeSegments.drawHeadSymbol(open: open, angle: angle)
        CGContextRestoreGState(context)
    }

    public class func drawTailSymbol(angle angle: CGFloat = 90) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let bodyColor2 = SnakeSegments.bodyColor.colorWithShadow(0.5)

        //// Polygon Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, 30, 30)
        CGContextRotateCTM(context, -(angle - 90) * CGFloat(M_PI) / 180)

        let polygonPath = UIBezierPath()
        polygonPath.moveToPoint(CGPoint(x: 24, y: 0))
        polygonPath.addLineToPoint(CGPoint(x: -25, y: 20.35))
        polygonPath.addLineToPoint(CGPoint(x: -25, y: -20.35))
        polygonPath.addLineToPoint(CGPoint(x: 24, y: 0))
        polygonPath.closePath()
        SnakeSegments.bodyColor.setFill()
        polygonPath.fill()
        bodyColor2.setStroke()
        polygonPath.lineWidth = 2
        polygonPath.stroke()

        CGContextRestoreGState(context)
    }

    public class func drawTail(angle angle: CGFloat = 90, bounds: CGRect = CGRect(x: 0, y: 0, width: 60, height: 60)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Symbol Drawing
        let symbolRect = CGRect(x: bounds.origin.x, y: bounds.origin.y, width: bounds.size.width, height: bounds.size.height)
        CGContextSaveGState(context)
        UIRectClip(symbolRect)
        CGContextTranslateCTM(context, symbolRect.origin.x, symbolRect.origin.y)
        CGContextScaleCTM(context, symbolRect.size.width / 60, symbolRect.size.height / 60)

        SnakeSegments.drawTailSymbol(angle: angle)
        CGContextRestoreGState(context)
    }

    public class func drawFoodSymbol() {
        //// Color Declarations
        let foodColor2 = SnakeSegments.foodColor.colorWithShadow(0.5)

        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRect(x: 18, y: 5, width: 25, height: 25))
        SnakeSegments.foodColor.setFill()
        ovalPath.fill()
        foodColor2.setStroke()
        ovalPath.lineWidth = 2
        ovalPath.stroke()


        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: 28, y: 27, width: 4, height: 28))
        SnakeSegments.foodColor.setFill()
        rectanglePath.fill()
        foodColor2.setStroke()
        rectanglePath.lineWidth = 2
        rectanglePath.stroke()


        //// Oval 2 Drawing
        let oval2Path = UIBezierPath(ovalInRect: CGRect(x: 5, y: 17, width: 25, height: 25))
        SnakeSegments.foodColor.setFill()
        oval2Path.fill()
        foodColor2.setStroke()
        oval2Path.lineWidth = 2
        oval2Path.stroke()


        //// Oval 3 Drawing
        let oval3Path = UIBezierPath(ovalInRect: CGRect(x: 30, y: 17, width: 25, height: 25))
        SnakeSegments.foodColor.setFill()
        oval3Path.fill()
        foodColor2.setStroke()
        oval3Path.lineWidth = 2
        oval3Path.stroke()
    }

    public class func drawFood(bounds bounds: CGRect = CGRect(x: 0, y: 0, width: 60, height: 60)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Symbol Drawing
        let symbolRect = CGRect(x: bounds.origin.x, y: bounds.origin.y, width: bounds.size.width, height: bounds.size.height)
        CGContextSaveGState(context)
        UIRectClip(symbolRect)
        CGContextTranslateCTM(context, symbolRect.origin.x, symbolRect.origin.y)
        CGContextScaleCTM(context, symbolRect.size.width / 60, symbolRect.size.height / 60)

        SnakeSegments.drawFoodSymbol()
        CGContextRestoreGState(context)
    }

    public class func drawBorderSymbol() {
        //// Color Declarations
        let borderColor = UIColor(red: 0.485, green: 0.485, blue: 0.485, alpha: 1.000)
        let borderColor2 = borderColor.colorWithShadow(0.5)

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRect(x: 5, y: 5, width: 50, height: 50), cornerRadius: 10)
        borderColor.setFill()
        rectanglePath.fill()
        borderColor2.setStroke()
        rectanglePath.lineWidth = 2
        rectanglePath.stroke()
    }

    public class func drawBorder(bounds bounds: CGRect = CGRect(x: 0, y: 0, width: 60, height: 60)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Symbol Drawing
        let symbolRect = CGRect(x: bounds.origin.x, y: bounds.origin.y, width: bounds.size.width, height: bounds.size.height)
        CGContextSaveGState(context)
        UIRectClip(symbolRect)
        CGContextTranslateCTM(context, symbolRect.origin.x, symbolRect.origin.y)
        CGContextScaleCTM(context, symbolRect.size.width / 60, symbolRect.size.height / 60)

        SnakeSegments.drawBorderSymbol()
        CGContextRestoreGState(context)
    }

    public class func drawMiddleSymbol() {
        //// Color Declarations
        let bodyColor2 = SnakeSegments.bodyColor.colorWithShadow(0.5)

        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRect(x: 5, y: 5, width: 50, height: 50))
        SnakeSegments.bodyColor.setFill()
        ovalPath.fill()
        bodyColor2.setStroke()
        ovalPath.lineWidth = 2
        ovalPath.stroke()
    }

    public class func drawMiddle(bounds bounds: CGRect = CGRect(x: 0, y: 0, width: 60, height: 60)) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Symbol Drawing
        let symbolRect = CGRect(x: bounds.origin.x, y: bounds.origin.y, width: bounds.size.width, height: bounds.size.height)
        CGContextSaveGState(context)
        UIRectClip(symbolRect)
        CGContextTranslateCTM(context, symbolRect.origin.x, symbolRect.origin.y)
        CGContextScaleCTM(context, symbolRect.size.width / 60, symbolRect.size.height / 60)

        SnakeSegments.drawMiddleSymbol()
        CGContextRestoreGState(context)
    }

}



extension UIColor {
    func colorWithHue(newHue: CGFloat) -> UIColor {
        var saturation: CGFloat = 1.0, brightness: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(nil, saturation: &saturation, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: newHue, saturation: saturation, brightness: brightness, alpha: alpha)
    }
    func colorWithSaturation(newSaturation: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, brightness: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(&hue, saturation: nil, brightness: &brightness, alpha: &alpha)
        return UIColor(hue: hue, saturation: newSaturation, brightness: brightness, alpha: alpha)
    }
    func colorWithBrightness(newBrightness: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, saturation: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getHue(&hue, saturation: &saturation, brightness: nil, alpha: &alpha)
        return UIColor(hue: hue, saturation: saturation, brightness: newBrightness, alpha: alpha)
    }
    func colorWithAlpha(newAlpha: CGFloat) -> UIColor {
        var hue: CGFloat = 1.0, saturation: CGFloat = 1.0, brightness: CGFloat = 1.0
        self.getHue(&hue, saturation: &saturation, brightness: &brightness, alpha: nil)
        return UIColor(hue: hue, saturation: saturation, brightness: brightness, alpha: newAlpha)
    }
    func colorWithHighlight(highlight: CGFloat) -> UIColor {
        var red: CGFloat = 1.0, green: CGFloat = 1.0, blue: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-highlight) + highlight, green: green * (1-highlight) + highlight, blue: blue * (1-highlight) + highlight, alpha: alpha * (1-highlight) + highlight)
    }
    func colorWithShadow(shadow: CGFloat) -> UIColor {
        var red: CGFloat = 1.0, green: CGFloat = 1.0, blue: CGFloat = 1.0, alpha: CGFloat = 1.0
        self.getRed(&red, green: &green, blue: &blue, alpha: &alpha)
        return UIColor(red: red * (1-shadow), green: green * (1-shadow), blue: blue * (1-shadow), alpha: alpha * (1-shadow) + shadow)
    }
}
